---
title: "CCR Triathlon 2021, 2022, 2023"
author: "Dexter Howard"
date: "4/10/2025"
output: html_document
---

## Load packages

```{r, include=FALSE}
library(tidyverse)
#library(climaemet) #for wind rose

# library(plotly) #for making ggplot interactive in "Viewer" window
# library(scales)
# library(patchwork)

```

Set up dates
```{r}

race_dates <- c(ymd("2021-06-06"), ymd("2022-06-05"), ymd("2023-06-04"))

dates_21 <- c(ymd("2021-06-01"), ymd("2021-06-06"), ymd("2021-06-09"))
dates_22 <- c(ymd("2022-06-02"), ymd("2022-06-06"), ymd("2022-06-09"), ymd("2022-07-07"))
dates_23 <- c(ymd("2023-06-01"), ymd("2023-06-04"), ymd("2023-06-07"), ymd("2023-06-29"))


```

## Read in EDI data sets

```{r}
ccr_met_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1105/3/df0ce4fc90f220b65c400b997abae37b")
ccr_dam_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/3/4afb209b30ebed898334badd3819d854" )
ccr_hobos_edi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/1069/3/4e83350e4189ec75d49b5ed3cbd766a8")
ysi <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/198/13/e50a50d062ee73f4d85e4f20b360ce4f")
chem <- read_csv("https://pasta.lternet.edu/package/data/eml/edi/199/12/a33a5283120c56e90ea414e76d5b7ddb")

```

## PPCPs
Making detection frequency plots 
THIS IS FOR ABOVE LIMIT OF DETECTION!!

```{r}
detect <- read.csv("../Data/Detection_frequency.csv")

#full years of data
detect |> 
  select(-DEET) %>%
  filter(Detection_frequency == "Full_year") |> 
  pivot_longer(-c(1:3), names_to = "PPCP", values_to = "value") |> 
  mutate(value = value*100) |> 
  ggplot(aes(x = as.factor(Year), y = value, fill = PPCP)) +
  geom_bar(stat = "identity", width = 0.75)+
  facet_wrap(~PPCP, nrow = 1)+
  labs(x = element_blank(), 
       y = "% of Samples above LLOD")+
  theme_classic()+ theme(legend.position = "top",
        axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold"))+
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73"))


#rying before and after
detect |> 
  select(-DEET) %>%
  filter(Detection_frequency == "Full_year") |> 
  pivot_longer(-c(1:3), names_to = "PPCP", values_to = "value") |> 
  mutate(value = value*100) |> 
  ggplot(aes(x = as.factor(Year), y = value, fill = PPCP)) +
  geom_bar(stat = "identity", width = 0.75)+
  facet_wrap(~PPCP, nrow = 1)+
  labs(x = element_blank(), 
       y = "% of Samples above LLOD")+
  theme_classic()+ theme(legend.position = "top",
        axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold"))+
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73"))



```


```{r}
acet_detect_21 <- (5/18)*100 
caff_detect_21 <- (18/18)*100
DEET_detect_21 <- (18/18)*100
Tric_detect_21 <- (14/18)*100

acet_detect_22 <- (3/24)*100
caff_detect_22 <- (24/24)*100
DEET_detect_22 <- (24/24)*100
Tric_detect_22 <- (0/24)*100

#!!!! Update 2023
acet_detect_23 <- (0/24)*100
caff_detect_23 <- (23/24)*100
DEET_detect_23 <- NA
Tric_detect_23 <- (10/24)*100

  
detectfreq <- data.frame(ppcp = c("Acetaminophen", "Triclosan", "Caffeine", "DEET"),
                         detection_21 = c(acet_detect_21, Tric_detect_21, caff_detect_21, DEET_detect_21),
                         detection_22 = c(acet_detect_22, Tric_detect_22, caff_detect_22, DEET_detect_22),
                         detection_23 = c(acet_detect_23, Tric_detect_23, caff_detect_23, DEET_detect_23))

detectfreq_long <- detectfreq %>% 
  pivot_longer(c(2:4))

detectfreq_long %>% 
  mutate(year = ifelse(name == "detection_21", 2021, NA),
         year = ifelse(name == "detection_22", 2022, year),
         year = ifelse(name == "detection_23", 2023, year)) %>% 
  filter(!ppcp == "DEET") %>%
  ggplot(aes(x = as.factor(year), y = value, fill = ppcp)) +
  geom_bar(stat = "identity", width = 0.75)+
  facet_wrap(~ppcp, nrow = 1)+
  labs(x = element_blank(), fill = "PPCP",
       y = "% of Samples above LLOD")+
  theme_classic()+ theme(legend.position = "top",
        axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold"))+
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73"))


```

Fig 2 by pre and post 

```{r}
#2021
acet_detect_21_before <- (0/6)*100 
acet_detect_21_after <- (5/12)*100 

tric_detect_21_before <- (3/6)*100
tric_detect_21_after <- (11/12)*100

caf_detect_21_before <- (6/6)*100
caf_detect_21_after <- (12/12)*100

#2022
acet_detect_22_before <- (0/6)*100
acet_detect_22_after <- (3/18)*100

caf_detect_22_before <- (6/6)*100
caf_detect_22_after <- (18/18)*100

tric_detect_22_before <- (0/6)*100
tric_detect_22_after <- (0/18)*100

#2023
acet_detect_23_before <- (0/6)*100
acet_detect_23_after <- (0/18)*100

caf_detect_23_before <- (6/6)*100
caf_detect_23_after <- (17/18)*100

tric_detect_23_before <- (0/6)*100
tric_detect_23_after <- (10/18)*100

  
detectfreq <- data.frame(ppcp = c("Acetaminophen", "Triclosan", "Caffeine"),
                         detection_21_before = c(acet_detect_21_before, Tric_detect_21_before, caff_detect_21_before),
                         detection_22_before = c(acet_detect_22_before, Tric_detect_22_before, caff_detect_22_before),
                         detection_23_before = c(acet_detect_23_before, Tric_detect_23_before, caff_detect_23_before))

detectfreq_long <- detectfreq %>% 
  pivot_longer(c(2:4))

detectfreq_long %>% 
  mutate(year = ifelse(name == "detection_21", 2021, NA),
         year = ifelse(name == "detection_22", 2022, year),
         year = ifelse(name == "detection_23", 2023, year)) %>% 
  filter(!ppcp == "DEET") %>%
  ggplot(aes(x = as.factor(year), y = value, fill = ppcp)) +
  geom_bar(stat = "identity", width = 0.75)+
  facet_wrap(~ppcp, nrow = 1)+
  labs(x = element_blank(), fill = "PPCP",
       y = "% of Samples above LLOD")+
  theme_classic()+ theme(legend.position = "top",
        axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold"))+
  scale_fill_manual(values=c("#E69F00", "#56B4E9", "#009E73"))


```


read in and line up PPCP data

```{r}
ppcp21_23 <- read.csv("../Data/PPCP_combined_formated.csv")

ppcp_forplotting <- ppcp21_23 %>% 
  mutate(Date = mdy(Date)) |> 
  pivot_longer(-c(1:4), names_to = "PPCP") |> 
  mutate(value = ifelse(value %in% c("<LLOD", "<LLOQ"), 0, value),
         value = ifelse(value == "> ULOQ", NA, value),
         value = as.numeric(value)) |> 
  pivot_wider(names_from = "PPCP", values_from = "value") |> 
  mutate(FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))) %>% 
  mutate(Site_name = ifelse(Site_number == 1, "Race Start", NA),
         Site_name = ifelse(Site_number == 2, "Race 2", Site_name),
         Site_name = ifelse(Site_number == 3, "Race 3", Site_name),
         Site_name = ifelse(Site_number == 4, "Race Finish", Site_name),
         Site_name = ifelse(Site_number == 5, "Downstream 1", Site_name),
         Site_name = ifelse(Site_number == 6, "Dam", Site_name)
         )


```


PPCP plots format 

```{r}

race_days_fakedate <- data.frame(
  Year = c(2021, 2022, 2023),
  intercept_date = as.Date(c("2030-06-06", "2030-06-05", "2030-06-04"))
)


### ACT
ppcp_forplotting |> 
  ggplot(aes(x = FakeDate, y = ACT_ngL, col = Site_name))+ # , shape = as.factor(Year)
  geom_point(size = 3)+
  geom_line(size = 1)+
  scale_x_date(limits = c(ymd("2030-05-31"), ymd("2030-07-10")), date_labels = "%b %d", 
               date_breaks = "7 days") +
  geom_vline(data = race_days_fakedate, aes(xintercept = intercept_date), linetype = 1)+
  labs(col = "Site", x = element_blank(),    y = "Acetaminophen (ng/L)")+
  facet_wrap(~Year, ncol = 1)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())



### TCS
ppcp_forplotting %>% 
  # filter(TCS_ngL < 50000) |> 
  ggplot(aes(x = FakeDate, y = TCS_ngL, col = Site_name))+ # , shape = as.factor(Year)
  geom_point(size = 3)+
  geom_line(size = 1)+
  scale_x_date(limits = c(ymd("2030-05-31"), ymd("2030-07-10")), date_labels = "%b %d", 
               date_breaks = "7 days") +
  geom_vline(data = race_days_fakedate, aes(xintercept = intercept_date), linetype = 1)+
  labs(col = "Site",   x = element_blank(),    y = "Triclosan (ng/L)")+
  scale_y_log10()+
  annotation_logticks(sides = "l")+
  geom_hline(yintercept = 50, linetype = 5)+
  facet_wrap(~Year, ncol = 1)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())



###CAF
ppcp_forplotting |> 
  ggplot(aes(x = FakeDate, y = CAF_ngL, col = Site_name))+ # , shape = as.factor(Year)
  geom_point(size = 3)+
  geom_line(size = 1)+
  scale_x_date(limits = c(ymd("2030-05-31"), ymd("2030-07-10")), date_labels = "%b %d", 
               date_breaks = "7 days") +
  geom_vline(data = race_days_fakedate, aes(xintercept = intercept_date), linetype = 1)+
  labs(col = "Site",       x = element_blank(),       y = "Caffeine (ng/L)")+
  scale_y_log10()+
  annotation_logticks(sides = "l")+
  facet_wrap(~Year, ncol = 1)+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())



## facet by variable and year

ppcp_forplotting %>% 
  select(FakeDate, Year, Site_name, ACT_ngL, CAF_ngL, TCS_ngL) %>% 
  pivot_longer(-c(1:3)) %>% 
  ggplot(aes(x = FakeDate, y = value, col = Site_name ))+
  geom_point()+  geom_line()+ 
  labs(x = "Date", y = "PPCP (ng/L)")+
  scale_y_log10()+
    geom_vline(data = race_days_fakedate, aes(xintercept = intercept_date), linetype = 1)+
  # annotation_logticks(sides = "l")+ #coord_cartesian(clip = "off")+
  facet_grid(Year~name, scales = "free_y")+
    facet_grid(name~Year, scales = "free_y")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())


### avg across sites

# ppcp_forplotting |>
#   select(1:8) |>
#   pivot_longer(-c(1:4)) |>
#   filter(name != "DEET_ngL") |>
#   group_by(Date, name) |>
#   summarise(mean = mean(value, na.rm = T),
#             min = min(value, na.rm = T),
#             max = max(value, na.rm = T)) |>
#     mutate(FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-")),
#          Year = year(Date)) |>
#   ggplot(aes(x = FakeDate, y = mean))+
#   geom_point()+  geom_line()+
#   geom_errorbar(aes(ymin = min, ymax = max))+
#   labs(x = "Date", y = "PPCP (ng/L)")+
#   scale_y_log10()+
#     geom_vline(data = race_days_fakedate, aes(xintercept = intercept_date), linetype = 1)+
#   facet_grid(Year~name, scales = "free_y")+
#     facet_grid(name~Year, scales = "free_y")+
#   theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
#                     panel.grid.major = element_blank(), panel.grid.minor = element_blank())



```

## New PPCP trials 

```{r}
head(ppcp_forplotting)

#CAF 
ppcp_forplotting |> 
  mutate(Pre_Post = ifelse(FakeDate < ymd("2030-06-03"), "Before", "Post")) |> 
  ggplot(aes(x = factor(Year), y = CAF_ngL, fill = Pre_Post)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  geom_jitter(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.8))+
  labs(x = "Year", y = "CAF (ng/L)", fill = "Period") +
  scale_y_log10()+
  #facet_wrap(~Site_number)+
  theme_minimal()

ppcp_forplotting |> 
  filter(Site_number == 3) |> 
  mutate(Pre_Post = ifelse(FakeDate < ymd("2030-06-03"), "Before", "Post")) |> 
  ggplot(aes(x = factor(Year), y = CAF_ngL, fill = Pre_Post)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  geom_jitter(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.8))+
  labs(x = "Year", y = "CAF (ng/L)", fill = "Period") +
  scale_y_log10()+
  theme_minimal()

#ACT
ppcp_forplotting |> 
  mutate(Pre_Post = ifelse(FakeDate < ymd("2030-06-03"), "Before", "Post")) |> 
  ggplot(aes(x = factor(Year), y = ACT_ngL, fill = Pre_Post)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  geom_jitter(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.8))+
  labs(x = "Year", y = "ACT (ng/L)", fill = "Period") +
  #facet_wrap(~Site_number)+
  theme_minimal()

#TCS
ppcp_forplotting |> 
  mutate(Pre_Post = ifelse(FakeDate < ymd("2030-06-03"), "Before", "Post")) |> 
  ggplot(aes(x = factor(Year), y = TCS_ngL, fill = Pre_Post)) +
  geom_boxplot(position = position_dodge(width = 0.8)) +
  geom_jitter(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.8))+
  labs(x = "Year", y = "TCS (ng/L)", fill = "Period") +
  #facet_wrap(~Site_number)+
  scale_y_log10()+
  theme_minimal()



#variable faceting 
ppcp_forplotting |> 
  mutate(Pre_Post = ifelse(FakeDate < ymd("2030-06-03"), "Before", "Post")) |> 
  select(Year, Site_number, Pre_Post, ACT_ngL, CAF_ngL, TCS_ngL ) |> 
  pivot_longer(-c(1:3), values_to = "conc_ngL", names_to = "PPCP") |>
  mutate(conc_ngL = ifelse(conc_ngL == 0, 0.1, conc_ngL)) |> 
  ggplot(aes(x = factor(Year), y = conc_ngL, fill = Pre_Post)) +
  geom_boxplot(
               position = position_dodge2(width = 0.8, preserve = "single")
               ) +
  geom_jitter(alpha = 0.5, position = position_jitterdodge(jitter.width = 0.1, dodge.width = 0.8))+
  labs(x = "Year", y = "Concentration (ng/L)", fill = "Period") +
  facet_wrap(~PPCP, nrow = 1)+
  scale_y_log10()+
  theme_bw()

  



```






## Meteorology data


```{r}

## format daily
ccr_met_daily <- ccr_met_edi |> 
  select(DateTime, Rain_Total_mm, ShortwaveRadiationUp_Average_W_m2, WindDir_degrees, WindSpeed_Average_m_s) |> 
  mutate(Date = as.Date(DateTime)) |> 
  group_by(Date) |> 
  summarise(Rain_daily_mm = sum(Rain_Total_mm, na.rm = T),
            SW_daily_mean = mean(ShortwaveRadiationUp_Average_W_m2, na.rm = T),
            WindDir_daily_mean = mean(WindDir_degrees, na.rm = T),
            WindSpeed_daily_mean = mean(WindSpeed_Average_m_s, na.rm = T)) 
  ## These lines work to calc cumulative rain but don't have full year for 2021
  # mutate(Year = year(Date)) |> 
  # group_by(Year) |> 
  # mutate(Rain_season = cumsum(Rain_daily_mm)) 

#plot daily full year
ccr_met_daily |> 
  pivot_longer(-1) |> 
  mutate(Year = year(Date), Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  filter(Year %in% c(2021,2022,2023)) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Year)))+
  geom_line(size = 1)+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  labs(x = "Date")+ scale_x_date(date_labels = "%b", date_breaks = "2 month")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 16),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())


#plot daily June
ccr_met_daily |> 
  pivot_longer(-1) |> 
  mutate(Year = year(Date), Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  filter(FakeDate >= ymd("2030-06-01"), FakeDate <= ymd("2030-06-30")) |> 
  filter(Year %in% c(2021,2022,2023)) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Year)))+
  geom_line(size = 1)+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  labs(x = "Date")+
  theme_bw()+ theme(legend.position = "top", #text = element_text(size = 15), legend.text = element_text(size=15),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())







```


wind roses 1 min data
```{r}
### resources from: https://ropenspain.github.io/climaemet/reference/ggwindrose.html

## full TS
  ggwindrose(
  speed = ccr_met_edi$WindSpeed_Average_m_s,
  direction = ccr_met_edi$WindDir_degrees,
  #speed_cuts = seq(0, 16, 4),
  legend_title = "Wind speed (m/s)",
  calm_wind = 0,
  n_col = 1,
  plot_title = "CCR Dam")+
  labs(subtitle = "2021-03-29 - 2024-12-31")


##June 2021
ccr_met_june21 <- ccr_met_edi |> 
  filter(DateTime >= ymd("2021-06-01"), DateTime < ymd("2021-07-01"))

  ggwindrose( speed = ccr_met_june21$WindSpeed_Average_m_s,  direction = ccr_met_june21$WindDir_degrees,
  speed_cuts = seq(0, 16, 4),
  legend_title = "Wind speed (m/s)",
  calm_wind = 0,  n_col = 1,
  plot_title = "CCR Dam")+ labs(subtitle = "June 2021")
  
##June 2022
ccr_met_june22 <- ccr_met_edi |> 
  filter(DateTime >= ymd("2022-06-01"), DateTime < ymd("2022-07-01"))

  ggwindrose( speed = ccr_met_june22$WindSpeed_Average_m_s,  direction = ccr_met_june22$WindDir_degrees,
  speed_cuts = seq(0, 16, 4),
  legend_title = "Wind speed (m/s)",
  calm_wind = 0,  n_col = 1,
  plot_title = "CCR Dam")+ labs(subtitle = "June 2022")
  
##June 2023
ccr_met_june23 <- ccr_met_edi |> 
  filter(DateTime >= ymd("2023-06-01"), DateTime < ymd("2023-07-01"))

  ggwindrose( speed = ccr_met_june23$WindSpeed_Average_m_s,  direction = ccr_met_june23$WindDir_degrees,
  speed_cuts = seq(0, 16, 4),
  legend_title = "Wind speed (m/s)",
  calm_wind = 0,  n_col = 1,
  plot_title = "CCR Dam")+ labs(subtitle = "June 2023")

## old wind rose
 #  library(openair)
 # chicago_wind = ccr_met%>%
 #   select(DateTime, WindSpeed_Average_m_s, WindDir_degrees)%>%
 #   filter(DateTime >= ymd("2021-05-31"), DateTime <= ymd("2021-06-10")) %>% 
 #   rename(date = DateTime, ws = WindSpeed_Average_m_s, wd = WindDir_degrees)
 # pollutionRose(chicago_wind, pollutant="ws")

```


## Dam data

Dam data

```{r}

#format daily 
ccr_dam_daily <- ccr_dam_edi |> 
  mutate(Date = as.Date(DateTime)) |> 
  filter(Date > ymd("2021-05-11")) |> 
  #select(Date, ThermistorTemp_C_1, ThermistorTemp_C_2, EXOTemp_C_1, EXOSpCond_uScm_1, EXODO_mgL_1, EXOChla_ugL_1, EXOfDOM_QSU_1, LvlDepth_m_13) |> 
  select(Date, ThermistorTemp_C_1, ThermistorTemp_C_2, EXOTemp_C_1, EXOSpCond_uScm_1, LvlDepth_m_13) |> 
  group_by(Date) |> 
  summarise(across(ThermistorTemp_C_1:LvlDepth_m_13, ~ mean(.x, na.rm = TRUE), .names = "{col}"))



#plot Year daily
ccr_dam_daily |> 
  select(-ThermistorTemp_C_1, -ThermistorTemp_C_2) |> 
  pivot_longer(-1) |> 
  mutate(Year = year(Date), Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  filter(Year %in% c(2021,2022,2023)) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Year)))+
  geom_line(size = 1)+
  geom_vline(xintercept = ymd("2030-06-05"))+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  labs(x = "Date")+ scale_x_date(date_labels = "%b", date_breaks = "2 month")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 16), 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())


#plot June daily
ccr_dam_daily |> 
  pivot_longer(-1) |> 
  mutate(Year = year(Date), Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  filter(FakeDate >= ymd("2030-06-01"), FakeDate <= ymd("2030-06-30"),
         Year %in% c(2021,2022,2023)) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Year)))+
  geom_line(size = 1)+
  geom_vline(xintercept = ymd("2030-06-05"))+
  facet_wrap(~name, nrow = 1, scales = "free_y")+
  labs(x = "Date")+
  theme_bw()+ theme(legend.position = "top", #text = element_text(size = 15), 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())



```

handheld sensors from 2021

```{r}
handhelds2021 <- read.csv("./Data/Field Measurments_YSI_pH_Cond.csv") |> 
  mutate(Date = as.Date(Date))

handhelds2021 |> 
  pivot_longer(-c(1:2)) |> 
  ggplot(aes(x = Date, y = value, color = as.factor(Site)))+
  geom_line()+
  facet_wrap(~name, scales = "free_y")

handheldsjoin <- handhelds2021 |> 
  group_by(Date) |> 
    summarise(across(2:8, ~ mean(.x, na.rm = TRUE), .names = "{col}")) |> 
  rename(SpCond_uScm = Spec_Cond_us_cm) |> 
  select(Date, Temp_C, SpCond_uScm)


##ysi 
ccrysi50 <- ysi |> 
  mutate(Date = as.Date(DateTime),
         Year = year(DateTime),
         Julian = yday(DateTime)) |> 
  filter(Reservoir == "CCR",
         Site == 50,
         Year %in% c(2021:2023)) |> 
  ggplot(aes(x = Julian, y = Temp_C, color = Depth_m))+
  geom_point()+
  facet_grid(Year~Site)
  
ccrysi50


```


## Meteo and Dam

```{r}
head(ccr_dam_daily)
head(ccr_met_daily)

left_join(ccr_met_daily, ccr_dam_daily, by = "Date") |> 
  select(-c(ThermistorTemp_C_1, ThermistorTemp_C_2)) |> 
  rename(Temp_C = EXOTemp_C_1,
         SpCond_uScm = EXOSpCond_uScm_1) |> 
  plyr::rbind.fill(handheldsjoin) |> 
  pivot_longer(-1) |> 
  mutate(Year = year(Date), Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  filter(FakeDate >= ymd("2030-05-01"), FakeDate <= ymd("2030-06-30"),
         Year %in% c(2021,2022,2023)) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Year)))+
  geom_point(size = 2)+
  geom_line(size = 1)+
  geom_vline(xintercept = ymd("2030-06-05"))+
  facet_wrap(~name, scales = "free_y", ncol = 4)+
  labs(x = "Date")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 16), 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())



```

################ DATA NOT USING 


## E. coli

```{r}
## read in and format data
ecoli2023 <- read.csv("E_coli_2023.csv") |> 
  mutate(Date = mdy(Date))

ecoli2021 <- read.csv("Chemisty (CNP) and E.coli for Ironman.csv") |> 
  select(Date, Site, Total_coliform_bacteria_MPN, E_coli_bacteria_MPN) |> 
  mutate(Date = ymd(Date))

#format E. coli so that the "< 1" values are numeric for plotting 
#I'm going to call "< 1" = 0.1 for the purpose of plotting, we should revisit this 
ecoli <- rbind(ecoli2021, ecoli2023) |> 
  filter(!is.na(Total_coliform_bacteria_MPN)) |> 
  mutate(E_coli_bacteria_MPN = as.numeric(ifelse(E_coli_bacteria_MPN %in% c("< 1", "<1"), 
                                               0.1, E_coli_bacteria_MPN))) %>% 
  mutate(Site_text = ifelse(Site == 1, "Race Start (1)", Site),
         Site_text = ifelse(Site == 2, "Race 2", Site_text),
         Site_text = ifelse(Site == 3, "Race 3", Site_text),
         Site_text = ifelse(Site == 4, "Race Finish (4)", Site_text),
         Site_text = ifelse(Site == 5, "Downstream 1 (5)", Site_text),
         Site_text = ifelse(Site == 6, "Downstream Dam (6)", Site_text))


#plot 
ecoli |> 
  select(Date, Site, Site_text, everything()) |> 
  pivot_longer(-c(1:3)) |> 
    mutate(Year = year(Date), Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Site_text) ))+
  geom_point(size = 1.5)+
  geom_line(size = 1)+
  labs(x = "Date", y = "Bacteria (MPN)", color = "Site")+
  facet_grid(name~Year, scales = "free_y")+
  scale_y_log10()+
    theme_bw()+ theme(legend.position = "top", text = element_text(size = 14),
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())


```


## A lab chem

```{r}
chem |> 
  filter(Reservoir == "CCR") |> 
  mutate(Date = as.Date(DateTime),
         Julian = yday(Date),
         Year = year(Date)) |> 
  filter(Year %in% c(2021,2022,2023),
         Site < 51) |> 
  select(Site, Year, Date, Julian, Depth_m, TN_ugL:DOC_mgL) |> 
  pivot_longer(-c(1:5)) |> 
  mutate(Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  #filter(FakeDate >= ymd("2030-05-01"), FakeDate <= ymd("2030-08-30")) |> 
  ggplot(aes(x = FakeDate, y = value, color = Depth_m, shape = as.factor(Site)))+
  geom_point()+
  facet_grid(name~Year, scales = "free_y")+
  geom_vline(xintercept = ymd("2030-06-05"))+
  labs(x = "Date")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 16), 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())



chem |> 
  filter(Reservoir == "CCR") |> 
  mutate(Date = as.Date(DateTime),
         Julian = yday(Date),
         Year = year(Date)) |> 
  filter(Year %in% c(2021,2022,2023),
         Site < 51,
         Depth_m == 0.1) |> 
  select(Site, Year, Date, Julian, Depth_m, TN_ugL:DOC_mgL) |> 
  pivot_longer(-c(1:5)) |> 
  mutate(Month = month(Date), Day = day(Date), 
         FakeDate = ymd(paste("2030", month(Date), day(Date), sep = "-"))
         ) |> 
  ggplot(aes(x = FakeDate, y = value, color = as.factor(Site)))+
  geom_point(size = 3)+
  facet_grid(name~Year, scales = "free_y")+
  geom_vline(xintercept = ymd("2030-06-05"))+
  labs(x = "Date")+
  theme_bw()+ theme(legend.position = "top", text = element_text(size = 16), 
                    panel.grid.major = element_blank(), panel.grid.minor = element_blank())


```




